version: '3'
services:
    docs:
        restart: unless-stopped
        build:
            context: .
        networks:
            - web
        env_file:
            - .env
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
networks:
    web:
        name: web
